fetchy dockerize --distribution ubuntu --codename bionic --exclude exclusions.txt --ppa deadsnakes --tag fetchy/python:2.5 python2.5
fetchy dockerize --distribution ubuntu --codename bionic --exclude exclusions.txt --ppa deadsnakes --tag fetchy/python:2.6 python2.6
fetchy dockerize --distribution ubuntu --codename bionic --exclude exclusions.txt --ppa deadsnakes --tag fetchy/python:2.7 python2.7
fetchy dockerize --distribution ubuntu --codename bionic --exclude exclusions.txt --ppa deadsnakes --tag fetchy/python:3.2 python3.2
fetchy dockerize --distribution ubuntu --codename bionic --exclude exclusions.txt --ppa deadsnakes --tag fetchy/python:3.3 python3.3
fetchy dockerize --distribution ubuntu --codename bionic --exclude exclusions.txt --ppa deadsnakes --tag fetchy/python:3.4 python3.4
fetchy dockerize --distribution ubuntu --codename bionic --exclude exclusions.txt --ppa deadsnakes --tag fetchy/python:3.5 python3.5
fetchy dockerize --distribution ubuntu --codename bionic --exclude exclusions.txt --ppa deadsnakes --tag fetchy/python:3.6 python3.6
fetchy dockerize --distribution ubuntu --codename bionic --exclude exclusions.txt --ppa deadsnakes --tag fetchy/python:3.7 python3.7
fetchy dockerize --distribution ubuntu --codename bionic --exclude exclusions.txt --ppa deadsnakes --tag fetchy/python:3.8 python3.8
